name: get-data

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *' # every hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compiling-data:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: setup-node
        uses: actions/setup-node@master

      - name: create .env file
        run: |
          touch .env
          echo PROFILE_NUMBER = ${{ secrets.PROFILE_NUMBER }} >> .env
          echo PROFILE_BASE_URL = ${{ secrets.PROFILE_BASE_URL }} >> .env
          

      - name: installing dependencies
        run: |
          npm install

      - name: fetch data
        run: |
          node index.js
          
      - name: Read uuid file
        id: getuuid
        run: echo "::set-output name=uuid::$(cat uuid.txt)"

      - name: update value
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'PROFILE_NUMBER'
          value: ${{ steps.getuuid.outputs.uuid }}
          repository: fojndnfjdjn/j-1
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
        
